-- 진료과별 UBIST 다처방 성분 데이터(종별 ubist_data와 별도 — 차원이 달라 혼합 시 이중집계).
CREATE TABLE IF NOT EXISTS public.ubist_specialty (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period          text NOT NULL,      -- YYYY-MM
  atc             text,
  manufacturer    text,               -- 판매사
  product_name    text,               -- 제품
  brand           text,               -- 브랜드
  ingredient      text,               -- 성분(기본명)
  ingredient_dose text,               -- 성분용량
  drug_code       text,               -- 약품코드
  specialty       text,               -- 진료과
  prescription_amount numeric,        -- 처방조제액(원)
  source_file     text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_us_period      ON public.ubist_specialty (period);
CREATE INDEX IF NOT EXISTS idx_us_period_spec ON public.ubist_specialty (period, specialty);
ALTER TABLE public.ubist_specialty ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ubist_specialty_service_all" ON public.ubist_specialty;
CREATE POLICY "ubist_specialty_service_all" ON public.ubist_specialty FOR ALL USING (true) WITH CHECK (true);

-- 진료과별 다처방 성분 집계(전년동월 vs 당월 + 아주약품 + 대조약).
CREATE OR REPLACE FUNCTION public.get_rx_trend(
  p_period text, p_prev text, p_specialty text, p_limit int
) RETURNS jsonb
LANGUAGE sql STABLE AS $$
  WITH base AS (
    SELECT btrim(lower(ingredient)) AS ing, period, manufacturer, product_name,
           COALESCE(prescription_amount, 0) AS amt
    FROM public.ubist_specialty
    WHERE period IN (p_period, p_prev)
      AND (p_specialty IS NULL OR specialty = p_specialty)
      AND ingredient IS NOT NULL AND ingredient <> ''
  ),
  cur  AS (SELECT ing, SUM(amt) tot FROM base WHERE period = p_period GROUP BY ing),
  prv  AS (SELECT ing, SUM(amt) tot FROM base WHERE period = p_prev   GROUP BY ing),
  aju  AS (SELECT ing, SUM(amt) tot FROM base WHERE period = p_period AND manufacturer = '아주약품' GROUP BY ing),
  ajut AS (SELECT DISTINCT ON (ing) ing, product_name FROM base WHERE period = p_period AND manufacturer = '아주약품' ORDER BY ing, amt DESC),
  refk AS (SELECT DISTINCT brand_key(item_name) bk FROM public.drug_reference WHERE item_name IS NOT NULL),
  refb AS (SELECT b.ing, b.product_name, b.amt FROM base b WHERE b.period = p_period AND brand_key(b.product_name) IN (SELECT bk FROM refk WHERE bk <> '')),
  ref  AS (SELECT ing, SUM(amt) tot FROM refb GROUP BY ing),
  reft AS (SELECT DISTINCT ON (ing) ing, product_name FROM refb ORDER BY ing, amt DESC),
  top  AS (SELECT ing, tot FROM cur ORDER BY tot DESC LIMIT p_limit)
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'ingredient', t.ing, 'cur', t.tot, 'prev', COALESCE(p.tot, 0),
    'aju', COALESCE(a.tot, 0), 'aju_product', at.product_name,
    'ref', COALESCE(r.tot, 0), 'ref_product', rt.product_name
  ) ORDER BY t.tot DESC), '[]'::jsonb)
  FROM top t
  LEFT JOIN prv p ON p.ing = t.ing
  LEFT JOIN aju a ON a.ing = t.ing
  LEFT JOIN ajut at ON at.ing = t.ing
  LEFT JOIN ref r ON r.ing = t.ing
  LEFT JOIN reft rt ON rt.ing = t.ing;
$$;
ALTER FUNCTION public.get_rx_trend(text, text, text, int) SET statement_timeout = '55s';

-- 이전(ubist_data 기반) 4파라미터 RPC 제거.
DROP FUNCTION IF EXISTS public.get_rx_trend(text, text, text, text, uuid, int);

CREATE OR REPLACE FUNCTION public.get_rx_trend_meta() RETURNS jsonb
LANGUAGE sql STABLE AS $$
  SELECT jsonb_build_object(
    'periods',     (SELECT COALESCE(jsonb_agg(DISTINCT period ORDER BY period DESC), '[]') FROM public.ubist_specialty WHERE period IS NOT NULL),
    'specialties', (SELECT COALESCE(jsonb_agg(DISTINCT specialty ORDER BY specialty), '[]') FROM public.ubist_specialty WHERE specialty IS NOT NULL)
  );
$$;
DROP FUNCTION IF EXISTS public.get_rx_trend_meta(uuid);
